{% set name = "openstep-parser" %}
{% set version = "1.5.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: f03c7fd9c78ac718c470cb0f667c1f09fa7f58786314f77fef8767302abe1658

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - nose
    - coverage
  run:
    - python >=3.6

test:
  imports:
    - openstep_parser

about:
  home: https://github.com/kronenthaler/openstep-parser
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: OpenStep plist reader into python objects
  description: |
    Parse Xcode projects directly using python. It doesn't require system command utilities.

extra:
  recipe-maintainers:
    - cav71
