{% set name = "openstep-parser" %}
{% set version = "2.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: bf7763599de5fc67bde55f6394d036fc5f8090deeead42948c8e6209a6033689

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - nose
    - coverage
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - openstep_parser

about:
  home: https://github.com/kronenthaler/openstep-parser
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: OpenStep plist reader into python objects
  description: |
    Parse Xcode projects directly using python. It doesn't require system command utilities.

extra:
  recipe-maintainers:
    - cav71
